name: 构建vless-ws

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Docker Hub用户名"
        required: true
        type: string
      docker_name:
        description: "Docker 镜像名称"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: ./vless-ws
          file: ./vless-ws/Dockerfile
          push: true
          tags: |
            ${{ github.event.inputs.username }}/${{ github.event.inputs.docker_name }}:latest
            ${{ github.event.inputs.username }}/${{ github.event.inputs.docker_name }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}